# Generated by Django 4.2.16 on 2024-09-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GH_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gh_username', models.CharField(max_length=100)),
                ('gh_activerepo', models.CharField(max_length=100)),
                ('gh_sessionkey', models.CharField(max_length=100)),
            ],
        ),
    ]
